export enum WsEvents {
  PLAYER_CONNECTED = 'player_connected',
  PLAYER_DISCONNECTED = 'player_disconnected',
  GUESS_SUBMIT = 'guess_submit',
  GUESS_RESULT = 'guess_result',
  GAME_STARTED = 'game_started',
  GAME_FINISHED = 'game_finished',
  PLAYER_GUESS_BROADCAST = 'player_guess_broadcast',
  GAME_STATE_UPDATE = 'game_state_update',
  PLAYER_JOINED = 'player_joined',
  PLAYER_LEFT = 'player_left',
  CREATE_ROOM = 'create_room',
  JOIN_ROOM = 'join_room',
  LEAVE_ROOM = 'leave_room',
  SET_READY = 'set_ready',
  GET_ROOMS = 'get_rooms',
  ADD_BOT = 'add_bot',
  REMOVE_BOT = 'remove_bot',
  AVAILABLE_ROOMS = 'available_rooms',
  ROOM_CREATED = 'room_created',
  ROOM_JOINED = 'room_joined',
  ROOM_STATE_UPDATE = 'room_state_update',
}
